version: "3"

services:
    database:
        image: mysql:latest
        volumes:
            - ./database/:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootwordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
            WORDPRESS_DEBUG: 1
    
    wordpress:
        depends_on:
           - database
        image: wordpress:latest
        volumes:
            - ./src/:/var/www/html/wp-content/
        ports:
            - "5000:80"
        restart: always
        environment:
            WORDPRESS_DB_HOST: database:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress